import os
import re
import shlex
import subprocess

from langchain_core.messages import HumanMessage
from langchain.agents import create_agent

from config import (
    BE_REPO_PATH,
    CURRENT_DATE,
    ARCHUNIT_MAX_RETRIES,
    ARCHUNIT_VALIDATION_ENABLED,
    ARCHUNIT_VALIDATION_COMMAND,
    GITHUB_BE_REPO,
)
from llm_factory import get_llm, is_stub_mode, get_provider_name
from state import SDLCState
from tools import list_directory, read_file, write_file, search_company_knowledge_base
from tools import git_commit_to_branch, create_github_pr


def _load_prompt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _slugify(text: str, default: str = "feature") -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:48] or default


def _detect_archunit_command() -> str:
    if ARCHUNIT_VALIDATION_COMMAND:
        return ARCHUNIT_VALIDATION_COMMAND

    mvnw = os.path.join(BE_REPO_PATH, "mvnw")
    gradlew = os.path.join(BE_REPO_PATH, "gradlew")

    if os.path.isfile(mvnw):
        return "./mvnw -q -Dtest=*ArchUnit* test"
    if os.path.isfile(gradlew):
        return "./gradlew test --tests *ArchUnit*"
    return ""


def _run_archunit_validation() -> tuple[bool, str]:
    command = _detect_archunit_command()
    if not command:
        return (
            False,
            "ArchUnit validation command not configured and no mvnw/gradlew detected in BE_REPO_PATH.",
        )

    try:
        command_args = shlex.split(command)
        completed = subprocess.run(
            command_args,
            cwd=BE_REPO_PATH,
            capture_output=True,
            text=True,
            timeout=900,
            check=False,
        )
    except Exception as exc:
        return (False, f"ArchUnit validation execution failed: {exc}")

    output = (completed.stdout or "") + \
        ("\n" + completed.stderr if completed.stderr else "")
    output = output.strip()
    if len(output) > 6000:
        output = output[:6000] + "\n...[truncated]"

    if completed.returncode == 0:
        return (True, f"ArchUnit validation passed. Command: {command}")

    return (
        False,
        f"ArchUnit validation failed (exit={completed.returncode}). Command: {command}\n{output}",
    )


def _invoke_be_generation(state: SDLCState, attempt: int, previous_failure: str | None) -> str:
    correction_block = ""
    if previous_failure:
        correction_block = (
            "\nARCHUNIT VALIDATION FAILURE (fix these issues before finishing):\n"
            f"{previous_failure}\n"
        )

    escalation_feedback = (state.get("human_escalation") or "").strip()
    escalation_block = ""
    if escalation_feedback:
        escalation_block = (
            "\nHUMAN ESCALATION FEEDBACK (priority guidance):\n"
            f"{escalation_feedback}\n"
        )

    prompt = f"""
    {_load_prompt("prompts/be_executor.md")}

    ARCHITECT PLAN:
    """
    {state['architect_plan']}
    """
    WORKSPACE PATH: {BE_REPO_PATH}
    TODAY'S DATE: {CURRENT_DATE} — use this date in any generated file headers, comments, or metadata.

    ATTEMPT: {attempt}
    Read the ARCHITECT PLAN carefully. Create exactly the files and folder structure it describes.
    Do not create any files not mentioned in the plan.

    IMPORTANT FOR THIS ATTEMPT:
    - Do NOT call git_commit_to_branch.
    - Do NOT call create_github_pr.
    - Only modify BE code/files to satisfy architecture and validations.
    {correction_block}
    {escalation_block}
    """

    llm = get_llm(temperature=0.1)
    agent = create_agent(
        llm,
        tools=[list_directory, read_file, write_file,
               search_company_knowledge_base],
    )
    result = agent.invoke({"messages": [HumanMessage(content=prompt)]})
    return result["messages"][-1].content


def _commit_and_open_pr(feature_text: str) -> tuple[str, str | None]:
    slug = _slugify(feature_text)
    branch = f"feat/be-{slug}"
    commit_result = git_commit_to_branch.invoke(
        {
            "repo_path": BE_REPO_PATH,
            "branch_name": branch,
            "commit_message": f"feat(be): implement {slug}",
        }
    )

    pr_result = create_github_pr.invoke(
        {
            "repo_name": GITHUB_BE_REPO or os.path.basename(BE_REPO_PATH),
            "branch_name": branch,
            "title": f"feat(be): {feature_text[:72]}",
            "pr_body": "Automated BE changes generated by SDLC agent after ArchUnit validation.",
        }
    )

    pr_url = None
    if isinstance(pr_result, str):
        match = re.search(r"https?://\S+", pr_result)
        if match:
            pr_url = match.group(0)

    return f"{commit_result}\n{pr_result}", pr_url


# Keywords that indicate a task has no backend work
_FE_ONLY_SIGNALS = (
    "no backend",
    "no backend changes",
    "backend changes required\n**none",
    "backend changes required\nnone",
    "pure frontend",
    "frontend-only",
    "frontend only",
    "no be changes",
    "backend: none",
)


def be_executor_node(state: SDLCState) -> SDLCState:
    plan_lower = state["architect_plan"].lower()
    if any(signal in plan_lower for signal in _FE_ONLY_SIGNALS):
        print(
            "\n⏭️  [BE Executor] Skipping — plan indicates no backend work required.")
        return {"be_output": "Skipped — frontend-only task."}

    print("\n⚙️ [BE Executor] Navigating to Backend Monorepo...")

    if is_stub_mode():
        msg = (
            f"Skipped in stub mode (provider={get_provider_name()}). "
            "No code generation executed."
        )
        print(f"   ↳ [BE Executor] {msg}")
        return {"be_output": msg}

    if not ARCHUNIT_VALIDATION_ENABLED:
        try:
            be_output = _invoke_be_generation(
                state, attempt=1, previous_failure=None)
            git_and_pr_output, pr_url = _commit_and_open_pr(
                state["user_request"])
            merged = f"{be_output}\n\n{git_and_pr_output}"
            result_state: SDLCState = {"be_output": merged}
            if pr_url:
                result_state["pr_urls"] = [pr_url]
            return result_state
        except Exception as e:
            be_output = f"BE agent failed: {str(e)}"
            print(f"   ❌ [BE Executor] Error: {e}")
            return {"be_output": be_output}

    # Fail fast when validation is required but no command is available.
    if not _detect_archunit_command():
        raise RuntimeError(
            "ArchUnit validation is enabled, but no validation command is configured. "
            "Set ARCHUNIT_VALIDATION_COMMAND or ensure mvnw/gradlew exists under BE_REPO_PATH."
        )

    max_attempts = max(1, ARCHUNIT_MAX_RETRIES + 1)
    previous_failure: str | None = None
    latest_be_output = ""

    for attempt in range(1, max_attempts + 1):
        print(
            f"   🔁 [BE Executor] ArchUnit loop attempt {attempt}/{max_attempts}")
        try:
            latest_be_output = _invoke_be_generation(
                state, attempt=attempt, previous_failure=previous_failure
            )
        except Exception as e:
            be_output = f"BE agent failed on attempt {attempt}: {str(e)}"
            print(f"   ❌ [BE Executor] Error: {e}")
            return {"be_output": be_output}

        passed, validation_output = _run_archunit_validation()
        if passed:
            print("   ✅ [BE Executor] ArchUnit validation passed")
            try:
                git_and_pr_output, pr_url = _commit_and_open_pr(
                    state["user_request"])
                merged = (
                    f"{latest_be_output}\n\n"
                    f"[ArchUnit]\n{validation_output}\n\n"
                    f"{git_and_pr_output}"
                )
                result_state: SDLCState = {"be_output": merged}
                if pr_url:
                    result_state["pr_urls"] = [pr_url]
                return result_state
            except Exception as e:
                err = f"ArchUnit passed but git/PR step failed: {e}"
                print(f"   ❌ [BE Executor] {err}")
                return {"be_output": f"{latest_be_output}\n\n{validation_output}\n\n{err}"}

        previous_failure = validation_output
        print(
            "   ⚠️  [BE Executor] ArchUnit validation failed; regenerating with failure context")

    final_output = (
        f"{latest_be_output}\n\n"
        "[ArchUnit]\n"
        f"Validation failed after {max_attempts} attempt(s).\n"
        f"Last failure:\n{previous_failure or 'No validation output captured.'}"
    )
    raise RuntimeError(final_output)
